# Generated by Django 2.2.6 on 2019-10-06 07:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Place_Order_Application', '0002_auto_20191006_0715'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='products',
        ),
        migrations.RemoveField(
            model_name='user',
            name='orders',
        ),
        migrations.AddField(
            model_name='order',
            name='user_who_placed_order',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Place_Order_Application.User'),
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Place_Order_Application.Category'),
        ),
    ]
