# Generated by Django 2.2.6 on 2019-10-06 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Place_Order_Application', '0003_auto_20191006_0731'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='products',
        ),
        migrations.AddField(
            model_name='order',
            name='products',
            field=models.ManyToManyField(to='Place_Order_Application.Product'),
        ),
    ]
