# Generated by Django 2.2.6 on 2019-10-06 18:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Place_Order_Application', '0004_auto_20191006_0751'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
